# Generated by Django 5.1.4 on 2025-01-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='services/images/')),
                ('body', models.TextField()),
            ],
        ),
    ]
