# Generated by Django 5.1.4 on 2025-01-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='title',
        ),
    ]
