# Generated by Django 5.1.4 on 2024-12-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='portfolio/banner')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='portfolio/image')),
                ('description', models.TextField()),
                ('summery', models.TextField()),
                ('designer', models.TextField()),
            ],
        ),
    ]
